dist: bionic

language: java

jdk:
 - oraclejdk9
 - openjdk10
 - oraclejdk11

sudo: required

before_install:
 - echo "before_install"

install:
 - echo "install"

before_script:
 - chmod +x test.sh

script:
 - javac -cp junit-4.12.jar:. PriorityQueueTest.java
 - java -cp junit-4.12.jar:hamcrest-core-1.3.jar: org.junit.runner.JUnitCore PriorityQueueTest

