os:
 - linux

dist:
 - bionic

language: java

jdk:
 - oraclejdk9
 - openjdk10
 - oraclejdk11

sudo: required

before_install:
 - echo "before_install"

install:
 - echo "install"

before_script:
 - chmod +x scripts/run-test.sh

script:
 - ./scripts/run-test.sh

after_script:
 - echo "after_script"

after_success:
 - echo "success"

after_failure:
 - echo "fail"
